### ISSUE TITLE
easier grammar 

### ISSUE THREAD

**Issue by kaleocheng** [kaleocheng/craftdot#1]
craftdot use yaml as it's config file now. it's good but I still want to see if there is a grammar can be easier than yaml.

yaml:

```yaml
dc-1:
  type: group
  sub-dc-1:
    type: group
    service-3:
      hosts:
        - host-5 172.0.0.5
  service-1:
    domains:
      - 1.example.com
    ports:
      - 8000
    hosts:
      - host-1 172.0.0.1
      - host-2 172.0.0.2
dc-2:
  type: group
  service-2:
    domains:
      - 2.example.com
    ports:
      - 8000
    hosts:
      - host-3 172.0.0.3
      - host-4 172.0.0.4

flows:
  - service-1 -> service-2
  - service-2 -> service-3
```

new grammar:

```
group dc-1{
    service-1 {
        domains {
            1.example.com
        }
        ports {
            8000
        }
        hosts {
            host-1 172.0.0.1
            host-2 172.0.0.2
        }
    }
    group sub-dc-1 {
        service-3 {
            hosts {
                host-5 172.0.0.5
            }
        }
    }
}

group dc-2 {
    service-2 {
        domains {
            2.example.com
        }
        ports {
            8000
        }
        hosts {
            host-3 172.0.0.3
            host-4 172.0.0.4
        }
    }
}

service-1 -> service-2
service-2 -> service-3
```
